/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Evermotion (https://sketchfab.com/evermotion)
license: SKETCHFAB Standard (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/air-conditioner-95f15c0088e44164be77e3155992b54d
title: air conditioner
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Aircon(props: any) {
  const group = useRef();
  const { nodes, materials }: any = useGLTF("./airmodel/scene.gltf");
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={0.035}
      position={props.position}
    >
      <group rotation={[-Math.PI / 2, 0, 1.6]} position={[0.47, -10, 1.8]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.47, 0, 1.8]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={
                nodes.archmodels74_051_001_archmodels74_051_001_0.geometry
              }
              material={materials.archmodels74_051_001}
            />
          </group>
          <group position={[0.47, 53.35, 1.8]}>
            <mesh
              geometry={
                nodes.archmodels74_051_002_archmodels74_051_002_0.geometry
              }
              material={materials.archmodels74_051_002}
            />
          </group>
          <group position={[0.47, 0, 1.8]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={
                nodes.archmodels74_051_003_archmodels74_051_003_0.geometry
              }
              material={materials.archmodels74_051_003}
            />
          </group>
          <group position={[0.47, 41.2, 8.33]} rotation={[-0.05, 0, 0]}>
            <mesh
              geometry={
                nodes.archmodels74_051_004_archmodels74_051_004_0.geometry
              }
              material={materials.archmodels74_051_004}
            />
          </group>
          <group position={[0.47, 40.28, 8.47]} rotation={[-0.05, 0, 0]}>
            <mesh
              geometry={
                nodes.archmodels74_051_005_archmodels74_051_005_0.geometry
              }
              material={materials.archmodels74_051_005}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./airmodel/scene.gltf");
