/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: yamazakiyuumi (https://sketchfab.com/yamazakiyuumi)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/free-softcream-icecream-3d-61a3049ce8ab48e09cc37bef628c8376
title: Free Softcream icecream 3Dモデル ソフトクリーム アイス
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function IceCream(props: any) {
  const group: any = useRef();
  const { nodes, materials }: any = useGLTF("./model/icecream/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-0.06, 9.57, -0.01]} scale={0.1}>
            <mesh
              geometry={nodes["���_���������������_0"].geometry}
              material={materials.material}
            />
            <mesh
              geometry={nodes["���_���������������001_0"].geometry}
              material={materials[".001"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./model/icecream/scene.gltf");
