/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Zilardar (https://sketchfab.com/Zilardar)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/stylized-house-66ea8904172f453098283706bb8afec8
title: Stylized house
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Office(props: any) {
  const group: any = useRef();
  const { nodes, materials }: any = useGLTF("./model/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null} position={[0.5, 0.5, 4.5]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.1}>
          <mesh
            geometry={nodes.LP1_house_0.geometry}
            material={nodes.LP1_house_0.material}
          />
          <mesh
            geometry={nodes.LP2_ground_0.geometry}
            material={nodes.LP2_ground_0.material}
          />
          <mesh
            geometry={nodes.LP3_karkas_0.geometry}
            material={nodes.LP3_karkas_0.material}
          />
          <mesh
            geometry={nodes.LP4_house_0.geometry}
            material={nodes.LP4_house_0.material}
          />
          <mesh
            geometry={nodes.LP5_karkas_0.geometry}
            material={nodes.LP5_karkas_0.material}
          />
          <mesh
            geometry={nodes.LP6_ground_0.geometry}
            material={nodes.LP6_ground_0.material}
          />
          <mesh
            geometry={nodes.LP7_karkas_0.geometry}
            material={nodes.LP7_karkas_0.material}
          />
          <mesh
            geometry={nodes.LP8_karkas_0.geometry}
            material={nodes.LP8_karkas_0.material}
          />
          <mesh
            geometry={nodes.LP9_karkas_0.geometry}
            material={nodes.LP9_karkas_0.material}
          />
          <mesh
            geometry={nodes.LP10_karkas_0.geometry}
            material={nodes.LP10_karkas_0.material}
          />
          <mesh
            geometry={nodes.LP11_karkas_0.geometry}
            material={nodes.LP11_karkas_0.material}
          />
          <mesh
            geometry={nodes.LP12_rocks_0.geometry}
            material={nodes.LP12_rocks_0.material}
          />
          <mesh
            geometry={nodes.LP13_rocks_0.geometry}
            material={nodes.LP13_rocks_0.material}
          />
          <mesh
            geometry={nodes.LP14_rocks_0.geometry}
            material={nodes.LP14_rocks_0.material}
          />
          <mesh
            geometry={nodes.LP15_props_0.geometry}
            material={nodes.LP15_props_0.material}
          />
          <mesh
            geometry={nodes.LP16_props_0.geometry}
            material={nodes.LP16_props_0.material}
          />
          <mesh
            geometry={nodes.LP17_rocks_0.geometry}
            material={nodes.LP17_rocks_0.material}
          />
          <mesh
            geometry={nodes.LP18_roof1_0.geometry}
            material={nodes.LP18_roof1_0.material}
          />
          <mesh
            geometry={nodes.LP19_roof1_0.geometry}
            material={nodes.LP19_roof1_0.material}
          />
          <mesh
            geometry={nodes.LP20_roof1_0.geometry}
            material={nodes.LP20_roof1_0.material}
          />
          <mesh
            geometry={nodes.LP21_roof1_0.geometry}
            material={nodes.LP21_roof1_0.material}
          />
          <mesh
            geometry={nodes.LP22_roof2_0.geometry}
            material={nodes.LP22_roof2_0.material}
          />
          <mesh
            geometry={nodes.LP23_roof2_0.geometry}
            material={nodes.LP23_roof2_0.material}
          />
          <mesh
            geometry={nodes.LP24_roof2_0.geometry}
            material={nodes.LP24_roof2_0.material}
          />
          <mesh
            geometry={nodes.LP25_roof2_0.geometry}
            material={nodes.LP25_roof2_0.material}
          />
          <mesh
            geometry={nodes.LP26_roof2_0.geometry}
            material={nodes.LP26_roof2_0.material}
          />
          <mesh
            geometry={nodes.LP27_props_0.geometry}
            material={nodes.LP27_props_0.material}
          />
          <mesh
            geometry={nodes.LP28_props_0.geometry}
            material={nodes.LP28_props_0.material}
          />
          <mesh
            geometry={nodes.LP29_props_0.geometry}
            material={nodes.LP29_props_0.material}
          />
          <mesh
            geometry={nodes.LP30_drova_0.geometry}
            material={nodes.LP30_drova_0.material}
          />
          <mesh
            geometry={nodes.LP31_drova_0.geometry}
            material={nodes.LP31_drova_0.material}
          />
          <mesh
            geometry={nodes.LP32_drova_0.geometry}
            material={nodes.LP32_drova_0.material}
          />
          <mesh
            geometry={nodes.LP33_drova_0.geometry}
            material={nodes.LP33_drova_0.material}
          />
          <mesh
            geometry={nodes.LP34_drova_0.geometry}
            material={nodes.LP34_drova_0.material}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./model/scene.gltf");
